### ISSUE TITLE
The --breakdown report crashes always

### ISSUE THREAD

**Issue by lars-t-hansen** [NAICNO/Jobanalyzer#102]
On current production data with current mainline code, but also on my dev system with older data:

```
$ ./sonalyze jobs --breakdown=host,command --data-path=data -u- -f8w
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/jobs.rs:170:73
```

Also with a smaller value for -f, and also with the default 1 day,

Same error with just `--breakdown=host`.

Different error (later in the pipeline) with `--breakdown=command`:

```
$ ./sonalyze jobs --breakdown=command --data-path=data -u-
thread 'main' panicked at 'assertion failed: summaries.len() == 1', src/jobs.rs:210:9
```

**Comment by lars-t-hansen** [comment]
There are fixes for this at larstha-breakdown-crasher that mostly make sense.  The underlying problem is that filtering is applied to raw candidate data in such a way that no data are available at nested levels of the breakdown, and that needs to be taken into account.  I think the fix is probably right as such, but I'm not happy with how this code works.

(The code has other problems, for example, breakdowns are presented even when there's only one item to show at the nested level.  This is "right" but silly and noisy.)
