### ISSUE TITLE
naicreport ml-cpuhog crashes

### ISSUE THREAD

**Issue by lars-t-hansen** [NAICNO/Jobanalyzer#220]
I've seen this before.  I think it's because a particular value in the database or an unexpected combination of state and data file causes an aux record not to be attached to its parent.  The deadweight report has the same issue (see further down)
```
panic: interface conversion: interface {} is nil, not *mlcpuhog.cpuhogJob

goroutine 1 [running]:
naicreport/mlcpuhog.makePerJobReport(0xc0000dfb20?)
	/itf-fi-ml/home/larstha/p/Jobanalyzer/naicreport/mlcpuhog/mlcpuhog.go:233 +0x246
naicreport/mlcpuhog.createCpuhogReport(0xc000116220, {0xedcaea200?, 0x0?, 0x0?}, 0x1)
	/itf-fi-ml/home/larstha/p/Jobanalyzer/naicreport/mlcpuhog/mlcpuhog.go:221 +0x125
naicreport/mlcpuhog.MlCpuhog({0x7ffdd845e15f?, 0xc0000cc730?}, {0xc000014090, 0x5, 0x5})
	/itf-fi-ml/home/larstha/p/Jobanalyzer/naicreport/mlcpuhog/mlcpuhog.go:179 +0xc4f
main.main()
	/itf-fi-ml/home/larstha/p/Jobanalyzer/naicreport/naicreport.go:29 +0xd0
```

```
panic: interface conversion: interface {} is nil, not *mldeadweight.deadweightJob

goroutine 1 [running]:
naicreport/mldeadweight.makePerJobReport(0xc0000dfb90?)
	/itf-fi-ml/home/larstha/p/Jobanalyzer/naicreport/mldeadweight/mldeadweight.go:196 +0x1da
naicreport/mldeadweight.createDeadweightReport(0xc00002a2f0, {0xedcaea200?, 0x0?, 0x0?}, 0x1)
	/itf-fi-ml/home/larstha/p/Jobanalyzer/naicreport/mldeadweight/mldeadweight.go:184 +0x125
naicreport/mldeadweight.MlDeadweight({0x7ffe07d8e166?, 0xc0000cc730?}, {0xc000014090, 0x5, 0x5})
	/itf-fi-ml/home/larstha/p/Jobanalyzer/naicreport/mldeadweight/mldeadweight.go:147 +0xc4f
main.main()
	/itf-fi-ml/home/larstha/p/Jobanalyzer/naicreport/naicreport.go:26 +0x171
```

**Comment by lars-t-hansen** [comment]
ReadJobDatabase creates records without the Aux field.  The Aux field should be set by the loop over EnsureJob, however, this does not iterate across the database but across information obtained from elsewhere.  If that information is partial - and it is, in this case - then some records will be skipped.  That leads to the later crash.

Possibly jobs in the database that have no backing in the logs (because the logs have been purged, as in this case) should be removed.

**Comment by lars-t-hansen** [comment]
This is tricky: what do we *want* to happen when the log file no longer shows a job?  This is the failing test case - the state has a job that is no longer present in a new log file.  For deadweight it seems simple: the job went away, we can purge.  For cpuhog, it may be less clear.  The job is no longer a hog?  It started using the GPU?  Can it come back?  It depends on policy.  Also, if any hiccup should prevent the creation of a log record we'll be expiring things that probably should not be expired.

I suspect the correct fix here is to purge when we are reporting, so that only reports are affected, not the state.  (My current patch purges too much, arguably.)

The bug only appears for json output - because this sets the "all records" flag; otherwise we only report jobs that have not already been reported.
