### ISSUE TITLE
Gracefully handle missing hosts in config

### ISSUE THREAD

**Issue by lars-t-hansen** [NAICNO/Jobanalyzer#263]
I had an instance where sonalyze panicked in unwrap() because a host could not be found in the info.  This type of error needs to be handled more gracefully.  Basically, MAILTO in the cron job should work, so it's sufficient to print a sensible error message and exit(1) probably.

New host names may be a fact of life in big systems, so arguably printing a sensible message to be seen by an admin and then *not* exiting is possibly even better.

**Comment by lars-t-hansen** [comment]
Local test case, this one crashes in unwrap (see further down for backtrace):
```
sonalyze/target/debug/sonalyze load --data-path ../tmp/test-data/mlx.hpc.uio.no -u- --config-file ../production/sonar-server/scripts/mlx.hpc.uio.no/mlx.hpc.uio.no-config.json --fmt=date,time,rcpu,rmem
```
when a host that is in the data has been removed from the config file.

Another one, this one does not crash but prints zeroes (and no warning message) for missing hosts:
```
sonalyze/target/debug/sonalyze jobs --data-path ../tmp/test-data/mlx.hpc.uio.no -u- --config-file ../production/sonar-server/scripts/mlx.hpc.uio.no/mlx.hpc.uio.no-config.json --fmt=job,user,duration,host,rcpu
```

Backtrace for crasher with RUST_BACKTRACE=full:
```
HOST: ml3.hpc.uio.no
thread 'main' panicked at src/load.rs:348:21:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x5565209855ac - std::backtrace_rs::backtrace::libunwind::trace::ha69d38c49f1bf263
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5565209855ac - std::backtrace_rs::backtrace::trace_unsynchronized::h93125d0b85fd543c
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5565209855ac - std::sys_common::backtrace::_print_fmt::h8d65f438e8343444
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5565209855ac - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h41751d2af6c8033a
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5565209ab76c - core::fmt::rt::Argument::fmt::h5db2f552d8a28f63
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/fmt/rt.rs:138:9
   5:     0x5565209ab76c - core::fmt::write::h99465148a27e4883
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/fmt/mod.rs:1114:21
   6:     0x556520982f2e - std::io::Write::write_fmt::hee8dfd57bd179ab2
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/io/mod.rs:1763:15
   7:     0x556520985394 - std::sys_common::backtrace::_print::h019a3cee3e814da4
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x556520985394 - std::sys_common::backtrace::print::h55694121c2ddf918
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x556520986913 - std::panicking::default_hook::{{closure}}::h29cbe3da3891b0b0
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:272:22
  10:     0x556520986634 - std::panicking::default_hook::h881e76b2b8c74280
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:292:9
  11:     0x556520986e95 - std::panicking::rust_panic_with_hook::hcc36e25b6e33969c
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:731:13
  12:     0x556520986d46 - std::panicking::begin_panic_handler::{{closure}}::ha415efb0f69f41f9
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:601:13
  13:     0x556520985ad6 - std::sys_common::backtrace::__rust_end_short_backtrace::h395fe90f99451e4e
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x556520986ae2 - rust_begin_unwind
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
  15:     0x556520681555 - core::panicking::panic_fmt::h452a83e54ecd764e
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
  16:     0x5565206815f3 - core::panicking::panic::h440670b29ba8362f
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:127:5
  17:     0x556520685070 - core::option::Option<T>::unwrap::h67eeb4a15edca018
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/option.rs:935:21
  18:     0x5565206c4225 - sonalyze::load::format_rcpu::hdf1645f4b1feebfe
                               at /home/larstha/p/Jobanalyzer/code/sonalyze/src/load.rs:348:13
  19:     0x556520711a4a - core::ops::function::Fn::call::h68f0810239ebe223
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:79:5
  20:     0x556520693c05 - core::ops::function::impls::<impl core::ops::function::Fn<A> for &F>::call::hbbec1e3115400a23
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:262:13
  21:     0x556520691a9d - sonalyze::format::format_data::{{closure}}::h4fd4f41cfe8c2e1c
                               at /home/larstha/p/Jobanalyzer/code/sonalyze/src/format.rs:146:23
  22:     0x5565207478c4 - <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::for_each::hbf5dc656ad9bbf61
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/slice/iter/macros.rs:254:21
  23:     0x5565206914d2 - sonalyze::format::format_data::h8f252887e922d140
                               at /home/larstha/p/Jobanalyzer/code/sonalyze/src/format.rs:143:5
  24:     0x5565206c2c91 - sonalyze::load::aggregate_and_print_load::h8d2d12513010e264
                               at /home/larstha/p/Jobanalyzer/code/sonalyze/src/load.rs:215:21
  25:     0x5565206a265f - sonalyze::sonalyze::h6e1862e0b7c5b83d
                               at /home/larstha/p/Jobanalyzer/code/sonalyze/src/sonalyze.rs:1433:50
  26:     0x55652069e8cc - sonalyze::main::h04c25c01e6e25f27
                               at /home/larstha/p/Jobanalyzer/code/sonalyze/src/sonalyze.rs:873:11
  27:     0x556520716aeb - core::ops::function::FnOnce::call_once::h40c56bca22747c9a
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:250:5
  28:     0x556520741d0e - std::sys_common::backtrace::__rust_begin_short_backtrace::h9af3a212919e7e54
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:154:18
  29:     0x5565206edfa1 - std::rt::lang_start::{{closure}}::hdf8076692db480da
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/rt.rs:166:18
  30:     0x55652097e06b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h14c5f6d1cd70a60f
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:284:13
  31:     0x55652097e06b - std::panicking::try::do_call::h2d02374ca451446a
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504:40
  32:     0x55652097e06b - std::panicking::try::h9f7922394bf57392
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468:19
  33:     0x55652097e06b - std::panic::catch_unwind::ha1600f9dd4ee7270
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142:14
  34:     0x55652097e06b - std::rt::lang_start_internal::{{closure}}::hfbd80e7d681b21a1
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/rt.rs:148:48
  35:     0x55652097e06b - std::panicking::try::do_call::heacaa33dbdaa16e0
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504:40
  36:     0x55652097e06b - std::panicking::try::h637875f7c9db85ea
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468:19
  37:     0x55652097e06b - std::panic::catch_unwind::h4caa9c0c78cb4c19
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142:14
  38:     0x55652097e06b - std::rt::lang_start_internal::h2d6a60ec944b523d
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/rt.rs:148:20
  39:     0x5565206edf7a - std::rt::lang_start::h53e2241ec3397419
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/rt.rs:165:17
  40:     0x5565206bff1e - main
  41:     0x7ff3187ea14a - __libc_start_call_main
  42:     0x7ff3187ea20b - __libc_start_main_impl
  43:     0x556520681e25 - _start
  44:                0x0 - <unknown>
```

**Comment by lars-t-hansen** [comment]
The current fix reliably signals an error now, when a relative field is needed and the host config is missing.
